package it.polimi.ingsw.resources;

public enum EventID {

    SET_GAME_PARAMETER,
    TURN_CYCLE_ORDER,
    UPDATE_BOARD,
    UPDATE_END_GAME_TOKEN,
    UPDATE_BAG,
    UPDATE_COMMON_GOAL_1_TOKEN_STACK,
    UPDATE_COMMON_GOAL_1_GIVEN_PLAYERS,
    UPDATE_COMMON_GOAL_2_TOKEN_STACK,
    UPDATE_COMMON_GOAL_2_GIVEN_PLAYERS,
    UPDATE_PLAYER_SHELVES,
    UPDATE_PLAYER_POINTS,
    START,
    CHOOSE_PLAYER_NAME,
    CHOOSE_IP_ADDRESS,
    CHOOSE_NEW_OR_JOIN,
    CHOOSE_NEW_GAME_NAME,
    CHOOSE_NEW_GAME_PLAYER_NUMBER,
    UPDATE_GAME_ROOM,
    UPDATE_GAME_ROOMS,
    NOTIFY_GAME_HAS_STARTED,
    CHOOSE_GAME_ROOM,
    GIVE_PERSONAL_GOALS,
    GIVE_COMMON_GOALS,
    PICK_TILES,
    CHOOSE_ORDER,
    CHOOSE_COLUMN,
    PLAYER_IS_PLAYING,
    ASSIGN_COMMON_GOAL_POINTS,
    ASSIGN_PERSONAL_GOAL_POINTS,
    ASSIGN_ADJACENT_GOAL_POINTS,
    ANNOUNCE_WINNER,
    JUST_SCAN_CHAT,
    JUST_PRINT_CHAT

}
