package it.polimi.ingsw.resources;

public enum MessageID {

    SHOW_ROOMS,
    SHOW_PERSONAL_ROOM,
    NOTIFY_GAME_HAS_STARTED,
    NEW_TURN_NEXT_PLAYER,
    PICK_ACCEPTED,
    INSERT_TILES_REQUEST,
    JOIN_ROOM,
    CREATE_NEW_ROOM,
    ASK_FOR_ROOMS,
    PICK_TILES_REQUEST,
    ROOM_NAME_NOT_AVAILABLE,
    ROOM_NOT_AVAILABLE,
    CHECK_ALIVE,
    PING,
    PONG,
    DISCONNECT_PLAYERS,
    HELLO,
    PLAYER_ACCEPTED,
    NEW_TURN_END_GAME, PLAYER_NOT_ACCEPTED

}
